version: '3.9'


services:
  db:
    image: postgres:16
    container_name: urbanflow_db
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10


  backend:
    build:
      context: .
      dockerfile: ./infra/docker/backend.Dockerfile
    container_name: urbanflow_backend
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
    ports:
      - "8000:8000"
    command: ["/app/entrypoint.sh"]
    volumes:
      - ./backend:/app


  agent:
    build:
      context: .
      dockerfile: ./infra/docker/agent.Dockerfile
    container_name: urbanflow_agent
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
    working_dir: /agent/hedera-agents
    volumes:
      - ./agent:/agent


  orchestrator:
    build:
      context: .
      dockerfile: ./infra/docker/orchestrator.Dockerfile
    container_name: urbanflow_orchestrator
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
      backend:
        condition: service_started
    command: ["node", "src/index.js"]
    volumes:
      - ./orchestrator:/usr/src/app
    ports:
      - "3005:3005" # si besoin pour un endpoint status

volumes:
  pgdata:
